CREATE TABLE emotions_log2 (

    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(255) NOT NULL, 
    cause VARCHAR(255) NOT NULL, 
    emotion VARCHAR(255) NOT NULL, 
    intensity INT(10) NOT NULL,
    thought1 VARCHAR(255) NOT NULL, 
    thought2 VARCHAR(255) NOT NULL, 
    thought3 VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL

)